Add upcycle ISA support
VerticalResearchGroup/eagle pull request #4
Opened 2022-03-29 22:06 UTC by manto128

Mike, can you please take a look?

2022-03-30 01:05 UTC, medav requested changes

2022-03-30 01:05 UTC, medav commented on photon/libphoton/photon/photon-arith.hh
> +static inline int8_t adds_i8(int8_t a,  int8_t b)  { int16_t c = (int32_t)a + (int32_t)b;
addition in int32 then cast to int16? I think we can just do the addition in int16

2022-03-30 01:05 UTC, medav commented on photon/libphoton/photon/photon-arith.hh
> +                                                        }
Can you re-indent these the following way:
```cpp
static inline int32_t adds_i32(int32_t a,  int32_t b)  { 
    int64_t c = (int64_t)a + (int64_t)b; 
    return (c > INT32_MAX) ? INT32_MAX : ((c < INT32_MIN) ? INT32_MIN : (int32_t)c);
}
```

I'd also recommend using `std::clamp`:
```cpp
static inline int32_t adds_i32(int32_t a,  int32_t b)  { 
    int64_t c = (int64_t)a + (int64_t)b; 
    return (int32_t)std::clamp(c, (int64_t)INT32_MIN, (int64_t)INT32_MAX);
}
```

2022-03-30 04:23 UTC, manto128 commented on photon/libphoton/photon/photon-arith.hh
> +                                                        }
This change needs "CXXOPTS:=-std=c++1z" to be set build.mk since clamp is supported in C++17. Do you want me to do it?

2022-03-30 23:28 UTC, medav commented on photon/libphoton/photon/photon-arith.hh
> +                                                        }
I'd say go for it -- first can you double check that the g++ on CSL machines supports c++17? I would hope yes but we have to cater to that common denominator

2022-03-31 00:39 UTC, medav requested changes

2022-03-31 00:39 UTC, medav commented on photon/libphoton/photon/photon-arith.hh
> +  int64_t c = (int64_t)a + (int64_t)b;
4-space indentation please

2022-03-31 00:40 UTC, manto128 commented on photon/libphoton/photon/photon-arith.hh
> +static inline int8_t adds_i8(int8_t a,  int8_t b)  { int16_t c = (int32_t)a + (int32_t)b;
Changed it to int32 in order to be consistent.

```c++
static inline int8_t adds_i8(int8_t a,  int8_t b) {
  int32_t c = (int32_t)a + (int32_t)b;
  return (int8_t)std::clamp(c, (int32_t)INT8_MIN, (int32_t)INT8_MAX);
}
```

2022-03-31 00:42 UTC, manto128 commented on photon/libphoton/photon/photon-arith.hh
> +                                                        }
I have added std::clamp and support for it by adding the C++17 flag in the build.mk

2022-03-31 00:58 UTC, manto128 commented on photon/libphoton/photon/photon-arith.hh
> +  int64_t c = (int64_t)a + (int64_t)b;
done

2022-04-04 02:38 UTC, closed without merging